version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
  keyed:
    build:
      context: .
      dockerfile: Dockerfile       
    ports:
      - "3000:3000"
